/*
  Based on: KeePass Password Safe - The Open-Source Password Manager
  Copyright (C) 2003-2017 Dominik Reichl <dominik.reichl@t-online.de>
  
  MSWifiImport - Plugin for importing Windows Wifi information.
  Copyright (C) 2017 Christopher R. Nerz <keepass@phoenixes.de>
  https://elgesl.github.io/keepass-mswifiimport/

  This program is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 3 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program; if not, write to the Free Software
  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

  The current version of the source code of the plugin can be found at
  https://github.com/elgesl/keepass-mswifiimport
*/

using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("MSWifiImportPlugin")]
[assembly: AssemblyDescription("Plugin for importing Wifi Connections saved in Windows or to export Wifi Connections" +
    " to Windows. Additionally, it can import (export) Wifi Connections to .xml files generated by (compatible with)" +
    " NetSH.\n" +
    "To generate/read the later use the command 'netsh wlan', e.g. 'netsh wlan export profile key=clear'.\n" +
    "Website: https://elgesl.github.io/keepass-mswifiimport/. Main icon designed by Freepik from Flaticon.")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Christopher R. Nerz")]
[assembly: AssemblyProduct("KeePass Plugin")]
[assembly: AssemblyCopyright("Copyright ©  2017 Christopher R. Nerz, main icon designed by Freepik from Flaticon")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

[assembly: ComVisible(false)]

// This GUID is generated by a random generator
[assembly: Guid("10d053f8-5648-4a0d-8967-da4682aa77ed")]

[assembly: AssemblyVersion("0.2.0.2")]
[assembly: AssemblyFileVersion("0.2.0.2")]
