using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("MSWifiImportPlugin")]
[assembly: AssemblyDescription("Plugin for importing Wifi Connections saved in Windows or to export Wifi Connections" +
    " to Windows. Additionally, it can import (export) Wifi Connections to .xml files generated by (compatible with)" +
    " NetSH.\n" +
    "To generate/read the later use the command 'netsh wlan', e.g. 'netsh wlan export profile key=clear'.\n" +
    "Main icon designed by Freepik from Flaticon")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Christopher R. Nerz")]
[assembly: AssemblyProduct("KeePass Plugin")]
[assembly: AssemblyCopyright("Copyright ©  2017 Christopher R. Nerz, main icon designed by Freepik from Flaticon")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// Setting ComVisible to false makes the types in this assembly not visible 
// to COM components.  If you need to access a type in this assembly from 
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM (generated by random generator)
[assembly: Guid("10d053f8-5648-4a0d-8967-da4682aa77ed")]

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Build Number
//      Revision
//
// You can specify all the values or you can default the Build and Revision Numbers 
// by using the '*' as shown below:
// [assembly: AssemblyVersion("1.0.*")]
[assembly: AssemblyVersion("0.2.0.0")]
[assembly: AssemblyFileVersion("0.2.0.0")]
